name: "publish"
<<<<<<< HEAD

=======
>>>>>>> 89a7528 (Update README and add GitHub Actions workflow)
on:
  push:
    branches:
      - main

<<<<<<< HEAD
# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

=======
>>>>>>> 89a7528 (Update README and add GitHub Actions workflow)
jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
<<<<<<< HEAD
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
=======
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
>>>>>>> 89a7528 (Update README and add GitHub Actions workflow)
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
<<<<<<< HEAD

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

=======
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
>>>>>>> 89a7528 (Update README and add GitHub Actions workflow)
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
<<<<<<< HEAD

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: bun install # change this to npm, pnpm or bun depending on which one you use.

=======
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: bun install
>>>>>>> 89a7528 (Update README and add GitHub Actions workflow)
      - uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "tauri-tools"
<<<<<<< HEAD
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
=======
          tagName: app-v__VERSION__
>>>>>>> 89a7528 (Update README and add GitHub Actions workflow)
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
